name = "newsnow-project"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "9a96ba1a-3536-4b7f-ac83-b63c52f0f722"
